apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  destination:
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 18.0.11
    chart: kafka
    helm:
      parameters:
        - name: zookeeper.enabled
          value: 'false'
        - name: replicaCount
          value: '1'
        - name: externalZookeeper.servers
          value: 'zookeeper'
        - name: externalZookeeper.servers
          value: 'zookeeper.zkafka.svc.cluster.local'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
