apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.21.0
    chart: vault
    helm:
      values: |
        global:
          tlsDisable: true
        server:
          auditStorage:
            enabled: true
          standalone:
            enabled: false
          ha:
            enabled: true
            replicas: 3
            config: |
              ui = true
              log_level = "Debug"
              listener "tcp" {
                tls_disable = true
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "consul" {
                path = "vault"
                address = "consul-consul-server.consul:8500"
              }
              seal "awskms" {
                region      = ""
                kms_key_id  = ""
                access_key  = ""
                secret_key  = ""
              }
              service_registration "kubernetes" {}

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
